# 
FROM python:3.9

# 
WORKDIR /api

# 
COPY api/requirements.txt /api/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /api/requirements.txt

# 
COPY api ./

# 
CMD ["fastapi", "run", "main.py", "--port", "8000"]